### PR TITLE
Request runtime permission

### LINKED ISSUE #3: Request sigspoof permission at runtime (if it is a runtime permission)
i haven't implemented this because -in my OS- sigspoof is not a runtime permission, so i can't test.

(haystack OS patching does not support patching as runtime permission at this time.)

### PR DESCRIPTION
**Pull request by SpiritCroc**
fixes https://github.com/Lanchon/sigspoof-checker/issues/3

### CODE REVIEW

**Comment by Lanchon** [comment]
AWESOME!!! i'll take a look asap

**Comment by Lanchon** [comment]
i merged, cleaned up a bit, documented, and updated version tags. so now let's hope f-droid picks up the change and outputs a build. i hope everything is ok, i can't really test this runtime permission with my setup. thanks again!

**Comment by SpiritCroc** [comment]
You're welcome!
I tested on AICP btw before and after this commit https://gerrit.aicp-rom.com/c/AICP/frameworks_base/+/65327 ; and now with version 1.1 again, seems fine.

**Comment by Lanchon** [comment]
thank you!!

**Comment by Lanchon** [comment]
FYI,
f-droid took a while to build, but the new version is live:
https://f-droid.org/packages/lanchon.sigspoof.checker/

**Pull request merged**
